### ISSUE TITLE
Arctic Witness Community Highlights Contribution

### ISSUE THREAD

**Issue by kameyer** [NCEAS/arctic-data-center#5]
Betsy Turner-Bogren would love for us to contribute to a spring issue of Arctic Witness Community Highlights.

Possible topics: news from recent workshops, information about any new services we provide to the community, or other sharable information 

Articles ~500 words of text plus a couple high resolution images with explanatory captions and a link or contact info to find further information.

Target submission for the next three issues:
- Tuesday, 20 February
- Monday, 19 March
- Friday, 20 April

**Comment by vlraymond** [comment]
oh, cool. 
ideas:
- [ ] recap of #lovedataweek, seeing as you'll have the content already
- [ ] showcase new data editor
- [ ] (later dates) showcase training materials via our training book

**Comment by kameyer** [comment]
I told Betsy we would contribute to the March issue (deadline Monday, 19 March) and we would share our new initiatives on highlighting specific datasets and PIs/researchers  on our website and twitter account. If there is information to share on the new data editor, we can share that, too.

**Comment by aebudden** [comment]
I think that is a great approach. We can use the data editor showcase in a future issue when we have some training resources to link to from the article.

**Comment by vlraymond** [comment]
emphasize range of skills we're supporting over next year:

entry level data management:
ESA 2018 / Polar 2018

technical training:
SB summer training

**Comment by kameyer** [comment]
First draft for March 19 article now available: https://docs.google.com/document/d/1VNtcovfEQIK8YVb2OTV4vKdRzY5BWpXo66jRPplLxiQ/edit - please provide edits! Thanks

**Comment by aebudden** [comment]
Some comments added, and some again just now :)

**Comment by kameyer** [comment]
Updated Draft Available: https://docs.google.com/document/d/1li3a8Q4_pmNuUzxjBH0sosVGuVFpFKttJMEpvMZzWEU/edit

**Comment by kameyer** [comment]
Vanessa has provided edits for this new draft, so it's been updated again (same link): https://docs.google.com/document/d/1li3a8Q4_pmNuUzxjBH0sosVGuVFpFKttJMEpvMZzWEU/edit Submitting on upcoming Monday, March 19

**Comment by kameyer** [comment]
Article submitted to Betsy on Wed March 21 https://docs.google.com/document/d/1li3a8Q4_pmNuUzxjBH0sosVGuVFpFKttJMEpvMZzWEU/edit
