### ISSUE TITLE
Dataset Highlight - Michael Ricketts

### ISSUE THREAD

**Issue by kameyer** [NCEAS/arctic-data-center#6]
Michael Ricketts is the first PI to respond to the outreach for highlighting datasets on the webpage. Plan is to have a Data highlights Page and create new posts with the different datasets. 

I've been working with Michael and sent him the first draft and page mock-up for his editing review.

Find both the text draft and a visual draft (also in draft on the Wordpress site) here: https://drive.google.com/drive/folders/1voi7RfEEB9P_sKik9GzUG0oXMYUtXmrA 

Arctic Data Center ->Outreach -> Website Data Highlights

**Comment by vlraymond** [comment]
added my comments to the document. Layout looks good. Thanks for doing this K, it's going to be great.

**Comment by aebudden** [comment]
This looks good. 
I see the addition of the dataset highlights section. Is this the best location for it? (Sorry if I missed the discussion). I wonder about 'Data' or an additional top level navigation for 'Community' which would include these highlights / profiles and also the Synthesis Group page? Is there a ticket for the website?

**Comment by kameyer** [comment]
I talked with Lauren this morning with regard to the Menu for the Data Highlights page. She said that we can do whatever we'd like, but suggested to minimize complexity by just adding it to an existing tab in a dropdown. But I really like your idea of a separate Menu tab for Community for both the highlights and Synthesis group page. It would be nice to be able to showcase them better via a separate tab.

At the moment I don't think there's a overarching ticket for website, but rather just different  tickets for individual website issues. I'm not sure if it's better to have them separate or all on one ticket
